<?php
/**
 * @file
 * Theme settings for the WordPress Content (wp) theme.
 *
 * This file provides the settings form for configuring WordPress theme options
 * when using the WP4BD WordPress-as-Engine compatibility layer.
 */

// Get available WordPress themes by scanning the directory
$themes_dir = backdrop_get_path('theme', 'wp') . '/wp-content/themes';
$available_themes = array();

if (is_dir($themes_dir)) {
  $theme_dirs = scandir($themes_dir);
  foreach ($theme_dirs as $dir) {
    if ($dir != '.' && $dir != '..' && is_dir($themes_dir . '/' . $dir)) {
      // Check if it has a style.css (basic theme validation)
      if (file_exists($themes_dir . '/' . $dir . '/style.css')) {
        // Try to read theme name from style.css
        $style_css = file_get_contents($themes_dir . '/' . $dir . '/style.css', false, null, 0, 500);
        if (preg_match('/Theme Name:\s*(.+)/i', $style_css, $matches)) {
          $theme_name = trim($matches[1]);
        } else {
          $theme_name = ucwords(str_replace(array('-', '_'), ' ', $dir));
        }
        $available_themes[$dir] = $theme_name;
      }
    }
  }
}

// Sort themes alphabetically by name
asort($available_themes);

// Add WordPress theme settings section
$form['wp4bd'] = array(
  '#type' => 'fieldset',
  '#title' => t('WordPress Theme Settings'),
  '#description' => t('Configure which WordPress theme to use for rendering content with the WP4BD WordPress-as-Engine compatibility layer.'),
  '#collapsible' => TRUE,
  '#collapsed' => FALSE,
);

$form['wp4bd']['active_theme'] = array(
  '#type' => 'select',
  '#title' => t('Active WordPress Theme'),
  '#description' => t('Select which WordPress theme to use for rendering content. The theme files should be placed in themes/wp/wp-content/themes/.'),
  '#options' => $available_themes,
  '#default_value' => theme_get_setting('wp4bd_active_theme', 'wp') ?: 'twentysixteen',
  '#required' => TRUE,
);

$form['wp4bd']['theme_directory'] = array(
  '#type' => 'textfield',
  '#title' => t('WordPress Themes Directory'),
  '#description' => t('Path to WordPress themes directory (relative to Backdrop root). Default: themes/wp/wp-content/themes'),
  '#default_value' => theme_get_setting('wp4bd_theme_directory', 'wp') ?: 'themes/wp/wp-content/themes',
  '#required' => TRUE,
);

// Store available themes for validation
$form['wp4bd']['available_themes'] = array(
  '#type' => 'value',
  '#value' => array_keys($available_themes),
);

// Add a submit handler to generate CSS when settings are saved
$form['#submit'][] = 'wp_theme_settings_submit';

/**
 * Submit handler for WordPress theme settings.
 */
function wp_theme_settings_submit($form, &$form_state) {
  // Generate active-theme.css file with @import to the selected theme
  $active_theme = $form_state['values']['active_theme'];
  $theme_path = backdrop_get_path('theme', 'wp');
  $css_file_path = $theme_path . '/active-theme.css';

  $css_content = "/* Auto-generated by WP theme settings - do not edit manually */\n";
  $css_content .= "/* Active WordPress theme: {$active_theme} */\n";
  $css_content .= "@import url(\"wp-content/themes/{$active_theme}/style.css\");\n";

  if (file_put_contents($css_file_path, $css_content) === FALSE) {
    backdrop_set_message(t('Warning: Could not write active-theme.css file.'), 'warning');
  } else {
    backdrop_set_message(t('Active theme CSS file generated for @theme', array('@theme' => $active_theme)));
  }

  backdrop_set_message(t('WordPress theme configuration has been saved.'));
  backdrop_flush_all_caches();
}